[[words]]
spelling = "îx"
pos = "Noun"
definitions = ["I", "me"]

[[words]]
spelling = "je"
pos = "Noun"
definitions = ["you"]

[[words]]
spelling = "zë"
pos = "Noun"
definitions = ["he", "him", "she", "her"]

[[words]]
spelling = "hæ"
pos = "Noun"
definitions = ["it"]